version: "3.3"

services:
    mysql:
      image: mysql:5.7
      container_name: ${PROJECT_NAME}-mysql
      environment:
        - MYSQL_ROOT_PASSWORD=MYSQL_ROOT_PASSWORD
        - MYSQL_DATABASE=url_shortener
        - MYSQL_USER=root
        - MYSQL_PASSWORD=MYSQL_ALLOW_EMPTY_PASSWORD
      ports:
        - "8306:3306"

    webserver:
      image: nginx
      container_name: ${PROJECT_NAME}-webserver
      ports:
        - "8000:80"

    php-fpm:
      build: docker/php-fpm
      container_name: ${PROJECT_NAME}-php-fpm
